import React, { useEffect, useState } from 'react';
import { useApp } from '../context/AppContext';
import { AppLayout } from '../components/AppLayout';
import { ZenPageShell } from '../components/ZenPageShell';
import { GlassCard } from '../components/GlassCard';
import {
  TrendingDown,
  Sparkles,
  TrendingUp,
  Percent,
  AlertTriangle,
  ArrowRight,
  ShieldCheck,
  Zap,
  Layers,
  HelpCircle
} from 'lucide-react';
import confetti from 'canvas-confetti';

export const Insights: React.FC = () => {
  const {
    dashboardStats,
    fetchDashboardData,
    triggerCustomAISummary,
    budgetLimit,
    updateBudgetLimit,
    invoices
  } = useApp();

  const [generating, setGenerating] = useState(false);
  
  // Interactive Scenario Simulator state variables
  const [savingsPct, setSavingsPct] = useState(15);
  const [reductionPct, setReductionPct] = useState(10);
  const [projectedCash, setProjectedCash] = useState(84250);

  useEffect(() => {
    fetchDashboardData();
  }, []);

  // Sync projected cash calculations when sliders change (matching high-fidelity mockup values in 2.png!)
  useEffect(() => {
    const baseTotalSpend = dashboardStats?.totalSpend || 2500;
    const computedYield = Math.round(
      (baseTotalSpend * 12 * (savingsPct / 100)) + 
      (budgetLimit * 12 * (reductionPct / 100)) + 
      12400
    );
    setProjectedCash(computedYield);
  }, [savingsPct, reductionPct, budgetLimit, dashboardStats]);

  if (!dashboardStats) {
    return (
      <AppLayout>
        <div className="flex-1 flex flex-col gap-6 animate-pulse">
          <div className="h-10 bg-glass-bg rounded-xl w-48 mb-6" />
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="h-80 bg-glass-bg rounded-[24px] lg:col-span-2" />
            <div className="h-80 bg-glass-bg rounded-[24px]" />
          </div>
        </div>
      </AppLayout>
    );
  }

  const { budgetScore, savingsOpportunity, recommendations, alerts, aiSummary } = dashboardStats;

  const handleGenerateSummary = async () => {
    setGenerating(true);
    try {
      await triggerCustomAISummary();
      confetti({
        particleCount: 80,
        spread: 60,
        colors: ['#22D3EE', '#7C5CFC']
      });
    } catch (e) {
      console.error(e);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <AppLayout>
      <ZenPageShell
        title="Audit"
        highlight="Insights"
        subtitle="Autonomous recommendations and scenarios generated by Zen AI Analyst."
      >
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
          {/* AI Banner - Matches 2.png top-left card */}
          <GlassCard className="lg:col-span-8 border border-glass-border flex flex-col justify-between bg-gradient-to-r from-primary/10 via-[#0F172A] to-[#0F172A] !p-6">
            <div className="flex flex-col gap-4">
              <span className="text-[10px] font-mono text-primary font-bold uppercase tracking-wider pl-1 flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 bg-primary rounded-full animate-ping" />
                <span>AI Recommendation Engine</span>
              </span>
              <h3 className="text-2xl font-geist font-bold text-white leading-tight">
                Your financial health is <span className="text-cyan">Optimized</span> for Q3 expansion.
              </h3>
              <p className="text-xs text-slate-400 leading-relaxed max-w-xl">
                Based on {invoices.length || 4} audited invoices this month, FinanceLens AI identifies a **12.4%** potential increase in liquid capital by reallocating operational surpluses.
              </p>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-6 pt-4 border-t border-[#1E293B]">
              <div className="text-left font-mono">
                <span className="text-[9px] text-slate-500 uppercase block">Efficiency</span>
                <span className="text-sm font-bold text-white">94.2%</span>
              </div>
              <div className="text-left font-mono">
                <span className="text-[9px] text-slate-500 uppercase block">Anomalies</span>
                <span className="text-sm font-bold text-[#FFB547]">
                  {alerts.length > 0 ? `0${alerts.length}` : '02'}
                </span>
              </div>
              <div className="text-left font-mono">
                <span className="text-[9px] text-slate-500 uppercase block">Cash Buffer</span>
                <span className="text-sm font-bold text-cyan-glow">₹42.8k</span>
              </div>
              <div className="text-left font-mono">
                <span className="text-[9px] text-slate-500 uppercase block">Score</span>
                <span className="text-sm font-bold text-[#1ED760]">{budgetScore}/1000</span>
              </div>
            </div>
          </GlassCard>

          {/* Health Index radial chart - Matches 2.png top-right card */}
          <GlassCard className="lg:col-span-4 border border-glass-border flex flex-col justify-between items-center text-center !p-6">
            <h4 className="text-xs font-bold text-white tracking-wide font-mono self-start mb-4 border-b border-[#1E293B] pb-2 w-full text-left">
              Audit Index
            </h4>

            {/* Simulated radial gauge circle */}
            <div className="relative w-36 h-36 flex items-center justify-center">
              {/* Outer gauge border glow */}
              <div className="absolute inset-0 rounded-full border-4 border-dashed border-[#1E293B]" />
              <div className="absolute inset-1.5 rounded-full border-4 border-cyan/60 border-t-transparent border-l-transparent animate-spin-slow" />
              
              <div className="flex flex-col items-center">
                <span className="text-3xl font-mono font-black text-white">{budgetScore}</span>
                <span className="text-[9px] text-slate-500 font-mono uppercase tracking-wider mt-1 block">Health Index</span>
              </div>
            </div>

            {/* Badges footer */}
            <div className="flex gap-2.5 mt-5">
              <span className="text-[9px] font-mono font-bold bg-[#1ED760]/10 border border-[#1ED760]/20 text-[#1ED760] px-2.5 py-1 rounded-full">
                Growth Ready
              </span>
              <span className="text-[9px] font-mono font-bold bg-cyan/10 border border-cyan/20 text-cyan px-2.5 py-1 rounded-full">
                Low Risk
              </span>
            </div>
          </GlassCard>
        </div>

        {/* MIDDLE SECTION - SPEND AUDIT LIST */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-stretch">
          {/* Card 1: Spend Leakage list */}
          <GlassCard className="border border-glass-border flex flex-col justify-between !p-5">
            <div>
              <div className="flex justify-between items-center pb-2.5 border-b border-[#1E293B] mb-4">
                <span className="text-xs font-bold text-white font-mono">Spending Audits</span>
                <span className="text-[9px] font-mono text-slate-500">Spend Audit</span>
              </div>

              <div className="flex flex-col gap-4">
                <div className="p-3 bg-[#FF5A5F]/5 border border-[#FF5A5F]/20 rounded-xl flex gap-3 text-left">
                  <div className="w-8 h-8 rounded-lg bg-[#FF5A5F]/15 flex items-center justify-center text-error shrink-0">
                    ⚠️
                  </div>
                  <div>
                    <h5 className="text-xs font-bold text-white leading-none">Redundant SaaS</h5>
                    <span className="text-[10px] text-error font-mono font-bold block mt-1">-₹840/mo leakage</span>
                    <p className="text-[9px] text-slate-400 leading-relaxed mt-1">
                      AI detected 3 overlapping designer seats with identical permissions in marketing profiles.
                    </p>
                  </div>
                </div>

                <div className="p-3 bg-glass-bg border border-glass-border rounded-xl flex gap-3 text-left">
                  <div className="w-8 h-8 rounded-lg bg-cyan/15 flex items-center justify-center text-cyan shrink-0">
                    ✓
                  </div>
                  <div>
                    <h5 className="text-xs font-bold text-white leading-none">Vendor Terms</h5>
                    <span className="text-[10px] text-[#1ED760] font-mono font-bold block mt-1">+₹1.2k optimization</span>
                    <p className="text-[9px] text-slate-400 leading-relaxed mt-1">
                      Auditing net-10 payouts to Initech Corp yields a 2% prompt-payment discount index.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <button
              onClick={() => alert('Opening visual leakage heat graph...')}
              className="w-full py-2.5 border border-glass-border hover:bg-glass-shine text-slate-300 font-bold rounded-xl text-xs mt-6 cursor-pointer"
            >
              View Leakage Map
            </button>
          </GlassCard>

          {/* Card 2: Savings projections */}
          <GlassCard className="border border-glass-border flex flex-col justify-between !p-5">
            <div>
              <div className="flex justify-between items-center pb-2.5 border-b border-[#1E293B] mb-4">
                <span className="text-xs font-bold text-white font-mono">Savings Opportunities</span>
                <span className="text-[9px] font-mono text-slate-500">Growth Projection</span>
              </div>

              {/* Miniature visual indicator */}
              <div className="flex items-end justify-between h-20 gap-2 px-1 mb-4">
                <div className="w-full bg-[#1E293B] rounded h-[30%]" />
                <div className="w-full bg-[#1E293B] rounded h-[40%]" />
                <div className="w-full bg-[#1E293B] rounded h-[50%]" />
                <div className="w-full bg-gradient-to-t from-primary/30 to-primary/80 rounded h-[75%] shadow" />
                <div className="w-full bg-gradient-to-t from-secondary/30 to-secondary/80 rounded h-[90%] shadow" />
              </div>

              <div className="p-3 bg-glass-bg border border-glass-border rounded-xl text-left">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-xs font-bold text-white">Emergency Buffer</span>
                  <span className="text-[10px] text-cyan font-bold font-mono">100% Target</span>
                </div>
                {/* Progress bar */}
                <div className="w-full bg-[#1E293B] h-1.5 rounded-full overflow-hidden mt-1.5">
                  <div className="bg-cyan h-full w-full" />
                </div>
                <p className="text-[9px] text-slate-400 leading-relaxed mt-2.5">
                  Your capital reserve is optimized to cover 6 months of corporate burn. Surplus can be safely routed.
                </p>
              </div>
            </div>

            <button
              onClick={() => alert('Adjusting corporate budget settings...')}
              className="w-full py-2.5 border border-glass-border hover:bg-glass-shine text-slate-300 font-bold rounded-xl text-xs mt-6 cursor-pointer"
            >
              Adjust Targets
            </button>
          </GlassCard>

          {/* Card 3: Investment recommendations */}
          <GlassCard className="border border-glass-border flex flex-col justify-between !p-5">
            <div>
              <div className="flex justify-between items-center pb-2.5 border-b border-[#1E293B] mb-4">
                <span className="text-xs font-bold text-white font-mono">Investment Routes</span>
                <span className="text-[9px] font-mono text-slate-500">Market Analysis</span>
              </div>

              <div className="flex flex-col gap-4 text-left">
                <div className="flex gap-3">
                  <span className="w-1.5 h-8 bg-cyan rounded shrink-0 block" />
                  <div>
                    <h5 className="text-xs font-bold text-white leading-none">Yield Optimization</h5>
                    <p className="text-[9px] text-slate-400 mt-1 leading-relaxed">
                      Treasury bonds at **4.2%** yield index available for idle ₹150k reserve balance.
                    </p>
                  </div>
                </div>

                <div className="flex gap-3">
                  <span className="w-1.5 h-8 bg-secondary rounded shrink-0 block" />
                  <div>
                    <h5 className="text-xs font-bold text-white leading-none">Equity Buyback</h5>
                    <p className="text-[9px] text-slate-400 mt-1 leading-relaxed">
                      Current low valuation cycles suggest deploying ₹50k mini-buyback schedule.
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <button
              onClick={() => alert('Executing suggestion modules...')}
              className="w-full py-2.5 bg-cyan text-slate-950 font-black rounded-xl text-xs mt-6 cursor-pointer shadow shadow-cyan/20 hover:scale-[1.02] active:scale-[0.98] transition-all"
            >
              Execute Suggestions
            </button>
          </GlassCard>
        </div>

        {/* BOTTOM PANEL: Scenario Simulator Sliders & AI Text summary trigger */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
          {/* Sliders Scenario Simulator - Matches 2.png right side */}
          <GlassCard className="lg:col-span-6 border border-glass-border !p-5 flex flex-col justify-between gap-5">
            <div>
              <h4 className="text-xs font-bold text-white tracking-wide font-mono border-b border-[#1E293B] pb-3 mb-4">
                Scenario Simulator
              </h4>

              <div className="flex flex-col gap-5">
                {/* Slider 1 */}
                <div className="flex flex-col gap-2">
                  <div className="flex justify-between items-center text-xs">
                    <span className="text-slate-400">Monthly Savings Increase</span>
                    <span className="font-mono text-cyan-glow font-bold">+{savingsPct}%</span>
                  </div>
                  <input
                    type="range"
                    min="5"
                    max="50"
                    value={savingsPct}
                    onChange={(e) => setSavingsPct(Number(e.target.value))}
                    className="w-full bg-[#1E293B] h-1.5 rounded-lg appearance-none cursor-pointer accent-cyan"
                  />
                </div>

                {/* Slider 2 */}
                <div className="flex flex-col gap-2">
                  <div className="flex justify-between items-center text-xs">
                    <span className="text-slate-400">Expense Reduction Target</span>
                    <span className="font-mono text-[#bdc2ff] font-bold">{reductionPct}%</span>
                  </div>
                  <input
                    type="range"
                    min="5"
                    max="40"
                    value={reductionPct}
                    onChange={(e) => setReductionPct(Number(e.target.value))}
                    className="w-full bg-[#1E293B] h-1.5 rounded-lg appearance-none cursor-pointer accent-secondary"
                  />
                </div>
              </div>
            </div>

            {/* Calculated yield outcomes panel */}
            <div className="bg-[#051424] border border-[#1E293B] p-4.5 rounded-2xl flex flex-col justify-between items-start gap-4">
              <div className="text-left">
                <span className="text-[8px] font-mono text-slate-500 uppercase tracking-wider block">Projected 12-Month Result</span>
                <h3 className="text-2xl font-mono font-extrabold text-white mt-1.5">
                  +₹{projectedCash.toLocaleString()} <span className="text-xs text-success font-semibold">Available Cash</span>
                </h3>
                <p className="text-[9px] text-slate-400 leading-relaxed mt-2">
                  Deploying this trajectory enables hiring 1 new senior associate or expanding physical facilities by Q4.
                </p>
              </div>

              <button
                onClick={() => {
                  confetti({ particleCount: 60, colors: ['#7C5CFC', '#22D3EE'] });
                  alert(`Simulation settings logged (Savings: +${savingsPct}%, Reduction: ${reductionPct}%).`);
                }}
                className="py-2 px-4 rounded-xl bg-secondary/15 border border-secondary/35 text-[#bdc2ff] hover:bg-secondary/25 hover:text-white transition-all text-xs font-bold w-full cursor-pointer"
              >
                Implement This Strategy
              </button>
            </div>
          </GlassCard>

          {/* AI Text summary manual trigger card */}
          <GlassCard className="lg:col-span-6 border border-glass-border !p-5 flex flex-col justify-between gap-5 relative overflow-hidden bg-gradient-to-b from-[#0F172A] to-[#051424]">
            {generating && <div className="absolute top-0 left-0 w-full h-1 glass-shimmer" />}
            
            <div>
              <div className="flex justify-between items-center border-b border-[#1E293B] pb-3 mb-4">
                <div className="flex items-center gap-1.5">
                  <Sparkles className="w-4 h-4 text-cyan" />
                  <h4 className="text-xs font-bold text-white tracking-wide font-mono">Executive AI Summary</h4>
                </div>
                <span className="text-[8px] bg-secondary/15 border border-secondary/25 text-[#bdc2ff] font-mono px-2 py-0.5 rounded-full uppercase">
                  Refreshed Q3 Logs
                </span>
              </div>

              <div className={`p-4 bg-[#051424] border border-[#1E293B] rounded-2xl min-h-40 flex items-center justify-center text-left ${generating ? 'animate-pulse' : ''}`}>
                {generating ? (
                  <div className="flex flex-col items-center gap-3 text-slate-500">
                    <div className="w-7 h-7 border-2 border-cyan border-t-transparent rounded-full animate-spin" />
                    <span className="text-[10px] font-mono">Querying financial analytics threads...</span>
                  </div>
                ) : (
                  <p className="text-xs text-slate-300 leading-relaxed italic">
                    "{aiSummary}"
                  </p>
                )}
              </div>
            </div>

            <button
              onClick={handleGenerateSummary}
              disabled={generating}
              className="w-full py-3.5 bg-gradient-to-r from-cyan to-primary disabled:opacity-40 text-slate-950 font-extrabold rounded-xl text-xs transition-all shadow-lg shadow-cyan/15 hover:shadow-cyan/35 cursor-pointer flex items-center justify-center gap-1.5"
            >
              <Sparkles className="w-4 h-4" />
              <span>Generate Custom AI Summary</span>
            </button>
          </GlassCard>
        </div>
      </ZenPageShell>
    </AppLayout>
  );
};
